name: Playwright E2E

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json', '**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-browsers
          restore-keys: |
            ${{ runner.os }}-playwright-browsers
      - name: Install deps
        run: npm ci
      - name: Set DATABASE_URL for Prisma
        run: echo "DATABASE_URL=file:./tmp/test.db" >> $GITHUB_ENV
      - name: Ensure tmp directory exists
        run: mkdir -p tmp
      - name: Generate prisma client
        run: npx prisma generate
      - name: Apply migrations / push schema
        run: npx prisma db push
      - name: Prepare DB
        env:
          DATABASE_URL: file:./tmp/test.db
        run: |
          npx prisma generate
          npx prisma db push
          npm run seed
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Prepare auth storage and run E2E via start-server-and-test
        env:
          DATABASE_URL: file:./tmp/test.db
          PORT: 3001
        run: |
          rm -f tests/e2e/storageState.json || true
          npm run auth:setup || true
          npx start-server-and-test "npm run dev" http://localhost:3001 "npx playwright test --config=playwright.config.ts"
